FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Copy application files
COPY . .

# Expose port for FastAPI
EXPOSE 8000

# Start the FastAPI application
CMD ["python", "main.py"]
