FROM python:3.11-slim

WORKDIR /app

COPY uploads/data.pdf /app/uploads/data.pdf
COPY secure-connect-store-base.zip /app/secure-connect-store-base.zip
COPY token.json /app/token.json

COPY . /app

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

